apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::229905369135:user/jackie-ci
      username: jackie-ci
      groups:
        - system:masters